# Generated by Django 5.1 on 2024-09-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_advocate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advocate',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
