# Generated by Django 5.1 on 2024-09-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_advocate_followers_advocate_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='twitterlink',
            field=models.CharField(default='', max_length=300),
        ),
    ]
